### ISSUE TITLE
Large projects hit buffer max

### ISSUE THREAD

**Issue by atmd83** [JamieMason/commit-release#1]
Ran commit-release on a large project, hit errors

npm i -g commit-release

commit-release

Error: stdout maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:244:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)

**Comment by djskinner** [comment]
Use child_process.spawn or increase the buffer size in the options passed to child_process.exec

**Comment by JamieMason** [comment]
Noticed this is actually a bug with https://github.com/domharrington/node-gitlog. There is an [exec and no maxBuffer setting](https://github.com/domharrington/node-gitlog/blob/master/index.js#L89) where they read the full git history.

Will raise an issue there once I get a sec.

**Comment by djskinner** [comment]
It happened for me because there was failed karma test output

**Comment by JamieMason** [comment]
Thanks @djskinner, I'll make the switch to spawn in here as well then.

**Comment by JamieMason** [comment]
Should handle large projects fine now, https://github.com/JamieMason/logservable is using spawn and streaming the git log as it reads it in.
